//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarkodluSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriVeresiye
    {
        public int ID { get; set; }
        public int MusteriID { get; set; }
        public string Ad { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string Eposta { get; set; }
        public decimal BorcTutari { get; set; }
        public System.DateTime veresiyeYazdirmaTarihi { get; set; }
        public Nullable<System.DateTime> veresiyeOdemeTarihi { get; set; }
        public string IslemTuru { get; set; }
    }
}
